language: java
script: mvn clean verify
sudo: false
jdk:
  - oraclejdk8
notifications:
  email: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "+extension RANDR"
  - sleep 3 # give xvfb some time to start