language: java
script: mvn clean verify
jdk:
  - oraclejdk8
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer