language: java
script: mvn clean verify
jdk:
  - oraclejdk8
  # Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
  addons:
      apt:
        packages:
        - oracle-java8-installer
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"